name: Create src package
env:
  app-name: 'smtube'
  
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ env.app-name }}

      - name: Get version
        run: |
            cd ${{ env.app-name }}
            ./get_version.sh
            VERSION=`cat version`
            rm version svn_revision
            echo "VERSION=$VERSION" >> $GITHUB_ENV
            echo "PACKAGENAME=${{ env.app-name }}-$VERSION" >> $GITHUB_ENV

      - name: Create package
        run: |
            mv ${{ env.app-name }} $PACKAGENAME
            tar --exclude=.svn --exclude=.git --exclude=.github -cvjf $PACKAGENAME.tar.bz2 $PACKAGENAME/
            ls -l
