name: Create src package
env:
  app-name: 'smtube'
  
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ env.app-name }}

      - name: List
        run: ls -l -R
